### ISSUE TITLE
Add Timescale Tagging

### ISSUE THREAD

**Issue by bkief** [imusmanmalik/cloudnative-pg-timescaledb-postgis-containers#20]
Consider adding the Timescale version to the image tag name. I am finding out (the hard way) that restoring a backup from running an image with and older version of Timescale is a challenge. Ideally the backup should restore to a server with the same Timescale version.

**Comment by imusmanmalik** [comment]
@bkief do you have any suggestions for this? at the moment TimescaleDB is 2.x 

https://github.com/imusmanmalik/cloudnative-pg-timescaledb-postgis-containers/blob/main/TimescaleDB-PostGIS/16/Dockerfile#L28

**Comment by bkief** [comment]
I've found that simply using the specific build number in the image tag is enough to hold the timescale version steady. eg `16-3.4-31`  

The root issue is that the timescale minor versions aren't compatible (2.11 vs 2.13) and pg_dump does not include the timescale version number. So when trying to restore a pg_dump database export, I was left trying to figure out what the original timescale version was, which was a problem when just using the tag `15-3.4` I think this can be closed
