### ISSUE TITLE
Add Timescale Toolkit to Image

### ISSUE THREAD

**Issue by bkief** [imusmanmalik/cloudnative-pg-timescaledb-postgis-containers#23]
Add the timescale hyperfunction toolkit to the build
https://docs.timescale.com/self-hosted/latest/tooling/install-toolkit/#install-toolkit-on-ubuntu-and-other-debian-based-systems
#22

**Comment by imusmanmalik** [comment]
> Add the timescale hyperfunction toolkit to the build
> 
> https://docs.timescale.com/self-hosted/latest/tooling/install-toolkit/#install-toolkit-on-ubuntu-and-other-debian-based-systems
> 
> #22 

Thanks alot for the contribution!

**Comment by imusmanmalik** [comment]
@markamber I believe the issue is more for including timescale toolkit not excluding it, so it should be there in all supported versions
