### ISSUE TITLE
Why not just have the shared_preload_libraries already set. 

### ISSUE THREAD

**Issue by chokosabe** [imusmanmalik/cloudnative-pg-timescaledb-postgis-containers#25]
Why not just have the shared_preload_libraries already set. The extra step to use the image feels unnecessary.

**Comment by imusmanmalik** [comment]
The reason for not setting shared_preload_libraries directly in the image is to provide flexibility for users to customize their PostgreSQL setup based on their specific requirements. This approach allows users to enable or disable extensions as needed without modifying the image itself, promoting a more versatile and adaptable deployment.
